package com.polytech.mystelven.servlet;

import com.polytech.mystelven.model.ProjectModel;
import org.apache.log4j.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 * Created by mystelven on 13/06/2015.
 */
@Named("SiteMapServlet")
@ApplicationScoped
public class SiteMapServlet extends HttpServlet {

    public static String getName() {
        return "sitemap";
    }

    protected Logger log() { return Logger.getLogger(this.getClass().getSimpleName()); }

    public void doGet(HttpServletRequest request, HttpServletResponse response) {

        StringBuilder xmlBuilder = new StringBuilder();

        xmlBuilder.append("\n<!-- All this sitemap.xml is generated by a Servlet, to be always up to date; -->\n\n");

        xmlBuilder.append("\n<!-- This is the home page of the website. -->\n");
        xmlBuilder.append("<url>\n" +
                "  <loc>http://valentin-montmirail.rhcloud.com/home</loc>\n" +
                "  <changefreq>daily</changefreq>\n" +
                "  <priority>1.00</priority>\n" +
                "</url>");

        xmlBuilder.append("\n<!-- This is the page to see my curriculum vitae. -->\n");
        xmlBuilder.append("<url>\n" +
                "  <loc>http://valentin-montmirail.rhcloud.com/curriculum-vitae</loc>\n" +
                "  <changefreq>daily</changefreq>\n" +
                "  <priority>0.9</priority>\n" +
                "</url>");

        xmlBuilder.append("<!-- This is the page to see the list of all my projects. -->\n");
        xmlBuilder.append("<url>\n" +
                "  <loc>http://valentin-montmirail.rhcloud.com/projects</loc>\n" +
                "  <changefreq>daily</changefreq>\n" +
                "  <priority>0.8</priority>\n" +
                "</url>");

        xmlBuilder.append("\n<!-- This is the page to see all my publications and my researches in general. -->\n");
        xmlBuilder.append("<url>\n" +
                "  <loc>http://valentin-montmirail.rhcloud.com/research</loc>\n" +
                "  <changefreq>daily</changefreq>\n" +
                "  <priority>0.8</priority>\n" +
                "</url>");

        xmlBuilder.append("\n<!-- This is the page to contact me. -->\n");
        xmlBuilder.append("<url>\n" +
                "  <loc>http://valentin-montmirail.rhcloud.com/contact</loc>\n" +
                "  <changefreq>daily</changefreq>\n" +
                "  <priority>0.8</priority>\n" +
                "</url>");

        xmlBuilder.append("<!-- This is the PDF to know what is exactly my thesis subject. -->\n");
        xmlBuilder.append("<url>\n" +
                "  <loc>http://valentin-montmirail.rhcloud.com/resources/pdf/sujet-these.pdf</loc>\n" +
                "  <changefreq>daily</changefreq>\n" +
                "  <priority>0.8</priority>\n" +
                "</url>");

        xmlBuilder.append("\n<!-- This is my Curriculum Vitae in a PDF format. -->\n");
        xmlBuilder.append("<url>\n" +
                "  <loc>http://valentin-montmirail.rhcloud.com/resources/pdf/Curriculum_Vitae_EN.pdf</loc>\n" +
                "  <changefreq>daily</changefreq>\n" +
                "  <priority>0.8</priority>\n" +
                "</url>");

        ProjectModel projectModel = ProjectModel.getProjectModel();

        ArrayList<String> projectIds = projectModel.getId();
        ArrayList<String> projectNames = projectModel.getNames();

        for(int i = 0; i < projectIds.size(); ++i) {
            xmlBuilder.append("\n<!-- This is the page to know more about : "+projectNames.get(i)+" -->\n");
            xmlBuilder.append("<url>\n" +
                    "  <loc>http://valentin-montmirail.rhcloud.com/viewProject?project=" + projectIds.get(i) + "</loc>\n" +
                    "  <changefreq>daily</changefreq>\n" +
                    "  <priority>0.6</priority>\n" +
                    "</url>");
        }

        PrintWriter writer = null;
        try {
            writer = response.getWriter();
        } catch (IOException e) {
            log().error(e.getMessage());
        }

        response.setContentType("text/xml;charset=UTF-8");
        writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");

        writer.write("<urlset\n" +
                "      xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"\n" +
                "      xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
                "      xsi:schemaLocation=\"http://www.sitemaps.org/schemas/sitemap/0.9\n" +
                "            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd\">");

        writer.write(xmlBuilder.toString());
        writer.write("</urlset>");
    }

    public void doPost(HttpServletRequest request, HttpServletResponse response) {

        doGet(request,response);
    }
}
